### Send POST request with json body
POST http://localhost:8082/create-developers
Content-Type: application/json

{
  "developerLevel": "SENIOR",
  "developerSkillType": "BACK_END",
  "experienceYears": 12,
  "memberId": "Micky",
  "name": "Mouse",
  "age": 23
}

